/**
 * Font Editor Window
 *
 * @requires modal
 *
 * @author Dinis Madeira (dinismadeira@tecnico.ulisboa.pt)
 * @version 2018
 */
 
'use strict';

let font = Uint8Array.from(atob('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAf+AA4HABgBgDAAwDMMwGMMYGAAYGAAYGP8YGP8YGP8YDH4wDDwwBgBgA4HAAf+AAH4AAAAAAAAAAAAAAAAAAAAAAAAAAH4AAf+AA//AB//gD//wDzzwHzz4H//4H//4HwD4HwD4HwD4D4HwD8PwB//gA//AAf+AAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4HAB8PgD+fwD//wD//wD//wD//wD//wB//gB//gA//AAf+AAP8AAH4AADwAABgAAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAf+AA//AB//gD//wD//wB//gA//AAf+AAP8AAH4AADwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAH4AAP8AAP8AAP8AAP8AB37gD//wH//4H+f4H8P4D8PwBzzgADwAADwAAH4AAP8AA//AAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAf+AA//AB//gB//gD//wD//wD//wD73wBzzgADwAADwAAH4AAP8AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AAf+AA//AA//AA//AA//AAf+AAf+AAP8AADwAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////8P//wD//gB//gB//AA//AA//AA//AA//gB//gB//wD//8P/////////////////////////AAAAAAAAAAAAAAAAAH4AAf+AA//AB4HgBwDgDgBwDgBwDgBwDgBwDgBwDgBwBwDgB4HgA//AAf+AAH4AAAAAAAAAAAAAAAAA/////////////////4H//gB//AA/+AAf+Dwf8H4P8P8P8P8P8P8P8P8P8H4P+Dwf+AAf/AA//gB//4H/////////////////AAAAAAAAAAAAAAAAAD/wAD/wAADwAAHwAPOwA/8wB/4wBw4wDgcwDgcwDgcADgcABw4AB/4AA/wAAPAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AAcOAA4HAA4HAA4HAA4HAAcOAAf+AAP8AADwAADwAADwAAf+AAf+AADwAADwAADwAADwAAAAAAAAAAAAAAAAAACAQADAwAD/wAD/wADgwADgwADgwADhwAD/gAD/AADgAADgAADgAAfgAB/gAD/gAD/gAD/AAD+AAB4AAAAAAAAAAAAAAAAAAAIAEAP/8AP/8AOAcAOAcAOAcAP/8AP/8AOAcAOAcAOAcAOAcAOB8AOH8A+P8D+P4H+PwH8HAH4AADgAAAAAAAAAAAAAAAAAAAAAAABgAABgABhhgBxjgA//AAf+AAcOAAYGAH4H4H4H4AYGAAcOAAf+AA//ABxjgBhhgABgAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAB4AAB+AAB/gAB/4AB/+AB//gB//gB/+AB/4AB/gAB+AAB4AABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAHgAAfgAB/gAH/gAf/gB//gB//gAf/gAH/gAB/gAAfgAAHgAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAf+AA//AADwAADwAADwAADwAADwAADwAA//AAf+AAP8AAH4AADwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAYGAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAYGAAAAAAAAAAYGAA8PAA8PAAYGAAAAAAAAAAAAAAAAAAAAAAAAAB//4D//4H3/4Hn/4HnngHnngHnngH3ngD/ngB/ngAHngAHngAHngAHngAHngAHngAHngAHngAAAAAAAAAAAAAAAAAAAAAAAAAP/AAf/gAcDwAcBwAOBwAPAAAfwAAf8AA8eAA8PAA8PAAePAAP+AAD+AAA8ADgcADgOADwOAB/+AA/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//gB//gB//gB//gB//gB//gAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAf+AA//AADwAADwAADwAADwAADwAADwAA//AAf+AAP8AAH4AADwAABgAA//AA//AAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAf+AA//AADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAA//AAf+AAP8AAH4AADwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAOAAAHAAADgD//wD//wAADgAAHAAAOAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAcAAA4AABwAAD//wD//wBwAAA4AAAcAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAB4AAB4AAB4AAB4AAB4AAB//gB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMMAAcOAA8PAB8PgD//wD//wB8PgA8PAAcOAAMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAABgAADwAADwAAH4AAH4AAP8AAP8AAf+AAf+AA//AA//AB//gB//gD//wD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wD//wB//gB//gA//AA//AAf+AAf+AAP8AAP8AAH4AAH4AADwAADwAABgAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAH4AAH4AAH4AAH4AAH4AAH4AAH4AADwAADwAABgAABgAAAAAAAAAABgAADwAADwAABgAAAAAAAAAAAAAAAAAAAAAAAAAA8PAA8PAA8PAA8PAA8PAAcOAAMMAAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcOAAcOAAcOAAcOAB//gB//gAcOAAcOAAcOAAcOAAcOAAcOAB//gB//gAcOAAcOAAcOAAcOAAAAAAAAAAAAAAAAAADwAADwAADwAADwAAP/AAf/AA8AAA4AAA4AAA8AAAf8AAP+AAAPAAAHAAAHAAAPAA/+AA/8AADwAADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAA8DAA8HAAYPAAAeAAA8AAB4AADwAAHgAAPAAAeGAA8PAA4PAAwGAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAf4AA88AA4cAA4cAA88AAf4AAPwAAPxgAe5wA8fwA4PwA4PgA4PAA4PAA8fAAf/gAP5wAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAADwAADwAAHgAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAB4AADwAAHgAAHAAAPAAAOAAAOAAAOAAAOAAAOAAAOAAAPAAAHAAAHgAADwAAB4AAA8AAAAAAAAAAAAAAAAAAAAAAAAAAPAAAHgAADwAAB4AAA4AAA8AAAcAAAcAAAcAAAcAAAcAAAcAAA8AAA4AAB4AADwAAHgAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAABgAAZmAAduAAP8AAH4AAH4AAP8AAduAAZmAABgAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAA//AA//AA//AA//AADwAADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAH4AAH4AAHwAAPgAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAH4AAH4AADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAADgAAHgAAPgAAfAAA+AAB8AAD4AAHwAAPgAAfAAA+AAB8AAB4AABwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AA8PAA4HAB4PgBwfgBw7gBxzgBzjgB3DgB+DgB8HgA4HAA8PAAf+AAP8AADwAAAAAAAAAAAAAAAAAAAAAAAAAABwAADwAAHwAAPwAAfwAA/wAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AA8PAA4HAA4HAAAHAAAPAAAeAAB8AAH4AAPwAAfAAAcAAA8AAA//AA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8fAA4PAAAHAAAHAAAHAAAPAAB+AAB+AAAPAAAHAAAHAAAHAA4PAA8fAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAOAAAeAAA+AAB+AAD+AAHeAAOeAAceAA4eAB//gB//gAAeAAAeAAAeAAAeAAB/gAB/gAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AA4AAA4AAA4AAA4AAA4AAA4AAA/8AA/+AAAPAAAHAAAHAAAHAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAB8AAH8AAP8AAeAAAcAAA4AAA4AAA4AAA/8AA/+AA8PAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAB//gB//gBwDgBwDgBwDgBwDgAAHgAAPAAAeAAA8AAB4AADwAAHgAAHgAAHgAAHgAAHgAAHgAAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AA8PAA8HAA8HAA+HAA/HAAf+AAf+AA4/AA4fAA4PAA4PAA8PAAf+AAP8AADwAAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AAcOAA4HAA4HAA4HAAcPAAf/AAP/AAD+AAAeAAAcAAA8AAB4AADwAAHgAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAH4AAH4AADwAAAAAAAAAAAAAAAAAADwAAH4AAH4AADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAH4AAH4AADwAAAAAAAAAAAAAAAAAADwAAH4AAH4AAD4AAB4AABwAADgAAHAAAAAAAAAAAAAAAAAAAAPAAAeAAA8AAB4AADwAAHgAAPAAAeAAA8AAA8AAAeAAAPAAAHgAADwAAB4AAA8AAAeAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AA//AAAAAAAAAA//AA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAeAAAPAAAHgAADwAAB4AAA8AAAeAAAPAAAPAAAeAAA8AAB4AADwAAHgAAPAAAeAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAAAHAAAPAAAeAAA8AAB4AADwAADwAADwAAAAAAAAAABgAADwAADwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAf+AA8PABwDgBgBgDj9wDH8wDOMwDMMwDMMwDMMwDOMwDn/wBj/wBwAAA8AAAf8AAH4AAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAeeAA8PAA4HAA4HAA4HAA4HAA//AA//AA4HAA4HAA4HAA4HAA4HAA4HAAAAAAAAAAAAAAAAAAAAAAAAAD/8AB/+AA4PAA4HAA4HAA4HAA4HAA4PAA/+AA/+AA4PAA4HAA4HAA4HAA4HAA4PAB/+AD/8AAAAAAAAAAAAAAAAAAAAAAAAAAD8AAP+AAf/AAeHgA8DgA4DgA4DgA4AAA4AAA4AAA4AAA4DgA4DgA8DgAeHgAf/AAP+AAD8AAAAAAAAAAAAAAAAAAAAAAAAAD/gAB/4AA48AA4eAA4OAA4PAA4HAA4HAA4HAA4HAA4HAA4HAA4PAA4OAA4eAA48AB/4AD/gAAAAAAAAAAAAAAAAAAAAAAAAAD//AB//AA4DAA4BAA4AAA4AAA4EAA4MAA/8AA/8AA4MAA4EAA4AAA4AAA4BAA4DAB//AD//AAAAAAAAAAAAAAAAAAAAAAAAAD//AB//AA4DAA4BAA4AAA4AAA4EAA4MAA/8AA/8AA4MAA4EAA4AAA4AAA4AAA4AAB8AAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAP+AAf/AA8HgA4DgB4DgBwAABwAABw/gBw/gBwDgBwDgB4DgA4DgA8HgAf/AAP+AAD8AAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA//AA//AA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAP8AADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAP8AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAfwAAHAAAHAAAHAAAHAAAHAAAHAAAHAAAHAAYHAA4HAA4HAA4HAA8PAA//AAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAD4PAB4PAA4OAA4eAA4cAA48AA44AA/4AA/wAA/wAA54AA54AA48AA48AA4eAA4eAB4PAD4PAAAAAAAAAAAAAAAAAAAAAAAAAD+AAB8AAA4AAA4AAA4AAA4AAA4AAA4AAA4AAA4AAA4AAA4AAA4HAA4HAA4HAA4HAB//AD//AAAAAAAAAAAAAAAAAAAAAAAAADAAwDgBwDwDwD4HwD8PwD+fwDv9wDn5wDjxwDhhwDgBwDgBwDgBwDgBwDgBwDgBwDgBwDgBwAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA8HAA8HAA+HAA+HAA/HAA/HAA7nAA7nAA53AA53AA4/AA4/AA4fAA4fAA4PAA4PAAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AA8PAA4HAB4HgBwDgBwDgBwDgBwDgBwDgBwDgB4HgA4HAA8PAAf+AAP8AADwAAAAAAAAAAAAAAAAAAAAAAAAAD/8AB/+AA4PAA4HAA4HAA4HAA4HAA4PAA/+AA/8AA4AAA4AAA4AAA4AAA4AAA4AAB8AAD+AAAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AA8PAA4HAB4HgBwDgBwDgBwDgBwDgBwDgBxzgB53gA53AA8/AAf+AAP+AAD+AAAOAAA/AAA/AAAAAAAAAAAAAD/8AB/+AA4PAA4HAA4HAA4HAA4HAA4PAA/+AA/8AA4eAA4PAA4HAA4HAA4HAA4HAB4HAD4HAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA8AAAfAAAP4AAH8AAB+AAAPAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAB//gB//gBjxgBDwgADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAH4AAP8AAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAAcOAAf+AAP8AAH4AAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAAcOAAcOAAOcAAOcAAH4AAH4AADwAADwAABgAABgAAAAAAAAAAAAAAAAAAAAAAAAADgBwDgBwDgBwDgBwDgBwDgBwDgBwDgBwDhhwDhhwDzzwDzzwB//gB//gA+fAA+fAAcOAAcOAAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAA8PAAeeAAP8AAH4AADwAADwAAH4AAP8AAeeAA8PAA4HAA4HAA4HAA4HAAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA8PAAeeAAP8AAH4AADwAADwAADwAADwAADwAADwAAH4AAP8AAAAAAAAAAAAAAAAAAAAAAAAAD//AD//AD//ADAPACAfAAA+AAB8AAD4AAHwAAPgAAfAAA+AAB8AAD4BADwDAD//AD//AD//AAAAAAAAAAAAAAAAAAAAAAAAAAP8AAP8AAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAOAAAP8AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAABwAAB4AAB8AAA+AAAfAAAPgAAHwAAD4AAB8AAA+AAAfAAAPgAAHgAADgAABgAAAAAAAAAAAAAAAAAAAAAAAAAP8AAP8AAAcAAAcAAAcAAAcAAAcAAAcAAAcAAAcAAAcAAAcAAAcAAAcAAAcAAAcAAP8AAP8AAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAeeAA8PAB4HgBwDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wD//wAAAAAAAAA8AAA+AAAfAAAPgAAHwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAP+AAAPAAAPAAP/AAf/AA8PAA4PAA4PAA8fAAf/gAPzwAAAAAAAAAAAAAAAAAAAAAAAAB+AAA+AAAeAAAeAAAeAAAeAAAf+AAf/AAePgAeHgAeHgAeHgAeHgAeHgAeHgAfPgA//AB5+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA4AAA4AAA4AAA4AAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAfAAAPAAAPAAAPAAAPAAP/AAf/AA+PAA8PAA8PAA8PAA8PAA8PAA8PAA+fAAf/gAPzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA+fAA8PAA//AA//AA8AAA8AAA8PAA+fAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAA+AAB/AADzgADhgADgAADgAADgAADgAAP4AAP4AADgAADgAADgAADgAADgAADgAAHwAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfngA//AB8eAB4eAB4eAB4eAB4eAB8eAA/+AAf+AAAeAAAeABweAB4+AA/8AAf4AAAAAAAAAD8AAB8AAA8AAA8AAA8AAA8AAA88AA9+AA/PAA+PAA8PAA8PAA8PAA8PAA8PAA8PAB8PAD8PAAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAADwAABgAAAAAAAAAAPwAAHwAADwAADwAADwAADwAADwAADwAADwAADwAAH4AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAPAAAPAAAGAAAAAAAAAAA/AAAfAAAPAAAPAAAPAAAPAAAPAAAPAAAPAAAPAAYPAA4PAA4PAA8fAAf+AAP8AAAAAAAAAD8AAD8AAA8AAA8AAA8AAA8AAA8PAA8eAA88AA94AA/wAA/4AA98AA8+AA8fAA8PAD8PAD8PAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAPwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAP8AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8PAD+fgD//wD//wDjzwDhhwDhhwDgBwDgBwDgBwDgBwDgBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AA/+AA8fAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADz8AB/+AA8fAA8PAA8PAA8PAA8PAA8PAA8PAA8fAA/+AA/8AA8AAA8AAB+AAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPzwAf/gA+PAA8PAA8PAA8PAA8PAA8PAA8PAA+PAAf/AAP/AAAPAAAPAAAfgAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8cAB8+AA9/AA/PAA+HAA8GAA8AAA8AAA8AAA8AAB+AAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA8AAAf8AAP+AAAPAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAGAAAOAAAOAAA/4AA/4AAOAAAOAAAOAAAOAAAOAAAOAAAOHAAPPAAH+AAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAA//AAf7gAPxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAAcOAAcOAAOcAAOcAAH4AAH4AADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgBwDgBwDgBwDgBwDxjwDxjwB73gB73gA//AA//AAeeAAeeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4HAA8PAAeeAAP8AAH4AADwAADwAAH4AAP8AAeeAA8PAA4HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAefAAP+AAH+AAA8AAA8AAB4AADwAA/gAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AAwPAAgeAAA8AAB4AADwAAHgAAPBAAeDAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAcAAA+AAB4AABwAABwAADwAAHgAAPAAAeAAAeAAAPAAAHgAADwAABwAABwAAB4AAA+AAAcAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAADwAADwAADwAADwAAAAAAAAAADwAADwAADwAADwAADwAADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAfAAAHgAADgAADgAADwAAB4AAA8AAAeAAAeAAA8AAB4AADwAADgAADgAAHgAAfAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAA+BgB/BwDzhwDhzwDg/gBgfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAAH4AAP8AAeeAA8PAB4HgB4HgB4HgB4HgB//gB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA//AA8PAA4HAA4HAA4HAA4AAA4AAA4AAA4AAA4HAA4HAA4HAA8PAA//AAf+AAP8AABwAABwAADwAAHwAAAAAAAAAAMMAAeeAAeeAAMMAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAA//AAfzgAPhwAAAAAAAAAAAAAAAAAAcAAA8AAB4AADwAAHgAAPAAAAAAAAAAAP8AAf+AA+fAA8PAA//AA//AA8AAA8AAA8PAA+fAAf+AAP8AAAAAAAAAAAAAAAAAADwAAH4AAP8AAeeAA8PAA4HAAAAAAAAAAP8AAf+AAAPAAAPAAP/AAf/AA8PAA4PAA4PAA8fAAf3gAPjwAAAAAAAAAAAAAAAAAAAAAAAAAMMAAeeAAeeAAMMAAAAAAAAAAP8AAf+AAAPAAAPAAP/AAf/AA8PAA4PAA4PAA8fAAf3gAPjwAAAAAAAAAAAAAAAAAOAAAPAAAHgAADwAAB4AAA8AAAAAAAAAAP8AAf+AAAPAAAPAAP/AAf/AA8PAA4PAA4PAA8fAAf3gAPjwAAAAAAAAAAAAAAAAADwAAH4AAGYAAGYAAH4AADwAAAAAAAAAAP8AAf+AAAPAAAPAAP/AAf/AA8PAA4PAA4PAA8fAAf3gAPjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA4AAA4AAA4AAA4AAA4HAA8PAAf+AAP8AADwAADwAAPwAAPwAADwAAH4AAP8AAeeAA8PAA4HAAAAAAAAAAP8AAf+AA+fAA8PAA//AA//AA8AAA8AAA8HAA+PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAMMAAeeAAeeAAMMAAAAAAAAAAP8AAf+AA+fAA8PAA//AA//AA8AAA8AAA8HAA+PAAf+AAP8AAAAAAAAAAAAAAAAAAOAAAPAAAHgAADwAAB4AAA8AAAAAAAAAAP8AAf+AA+fAA8PAA//AA//AA8AAA8AAA8HAA+PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAMMAAeeAAeeAAMMAAAAAAAAAAPwAAPwAADwAADwAADwAADwAADwAADwAADwAADwAAP8AAP8AAAAAAAAAAAAAAAAAADwAAH4AAP8AAeeAA8PAA4HAAAAAAAAAAPwAAPwAADwAADwAADwAADwAADwAADwAADwAADwAAP8AAP8AAAAAAAAAAAAAAAAAA4AAA8AAAeAAAPAAAHgAADwAAAAAAAAAAPwAAPwAADwAADwAADwAADwAADwAADwAADwAADwAAP8AAP8AAAAAAAAAAAAAAAAAAAAAAMMAAeeAAeeAAMMAAAAAABgAADwAAH4AAP8AAeeAA8PAA8PAA8PAA//AA//AA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAADwAAH4AAGYAAGYAAH4AADwAAAAAADwAAH4AAP8AAeeAA8PAA8PAA8PAA//AA//AA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAAcAAA8AAB4AADwAAHgAAPAAAAAAA//AA//AA8DAA8BAA8AAA/8AA/8AA/8AA8AAA8BAA8DAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+fAD//gAD5wADwwA//wB//wDnwADnwADnwADn4wD+fwB8PgAAAAAAAAAAAAAAAAAAAAAAAAAD/gAH/gAP4AAf4AA94AB54ABx4ABx4AB//AB//ABx4ABx4ABx4ABx4ABx4ABx4ABx/gBx/gAAAAAAAAAAAAAAAAADwAAH4AAP8AAeeAA8PAA4HAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAMMAAeeAAeeAAMMAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAA4AAA8AAAeAAAPAAAHgAADwAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAADwAAH4AAP8AAeeAA8PAA4HAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAA//AAf7gAPxwAAAAAAAAAAAAAAAAAOAAAPAAAHgAADwAAB4AAA8AAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAA//AAf7gAPxwAAAAAAAAAAAAAAAAAAAAAAAAAMMAAeeAAeeAAMMAAAAAAAAAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAefAAP+AAH+AAA8AAA8AAB4AADwAA/gAAfAAAMMAAeeAAeeAAMMAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAMMAAeeAAeeAAMMAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAA//AAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAAP8AAeeAA8PAA8PAA8AAA8AAA8AAA8AAA8PAA8PAAf+AAP8AADwAADwAADwAADwAAAAAAAAAAH+AAP/AAfHgAeDgAeAAAeAAAeAAAeAAAeAAAeAAA/+AB/8AAeAAAeAAAeAAAeAAA8AAB4AAB//AB//gAAAAAAAAAAAAAAAAA8PAA8PAA8PAA8PAA8PAA8PAAeeAAP8AAH4AADwAADwAA//AAf+AADwAADwAA//AAf+AADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAPwAAP4AAO8AAOcAAOc4AOc4AOc4AO84AP7/AP3/AOA48OA58OA5wOA54OA48OA4cOA58OA54AAAAAAAAAAAAAAAAAA/AAB/gAD7wADxwADwAADwAADwAADwAA//AA//AADwAADwAADwAADwAADwAADwAADwAAnwAA/gAAfAAAAAAAAAAAAAAAAAAAA8AAB8AAD4AAHwAAPgAAPAAAAAAAAAAAH8AAP+AAAPAAAPAAP/AAf/AA8PAA4PAA4PAA8fAAf3gAPjwAAAAAAAAAAAAAAAAAA8AAB8AAD4AAHwAAPgAAPAAAAAAAAAAAPwAAHwAADwAADwAADwAADwAADwAADwAADwAADwAAH4AAP8AAAAAAAAAAAAAAAAAAA8AAB8AAD4AAHwAAPgAAPAAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAA8AAB8AAD4AAHwAAPgAAPAAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAA//AAf7gAPxwAAAAAAAAAAAAAAAAAAAAAAAAAfDgA/ngB5/ABw+AAAAAAAAAA/8AA/+AA8fAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAfDgA/ngB5/ABw+AAAAAAAAAAwHAA4HAA8HAA+HAA/HAA/nAA/3AA7/AA5/AA4/AA4fAA4PAA4HAA4DAAAAAAAAAAAAAAAAAAAAAAAAAAf4AAf8AAAeAA/+AB/+AB4eAB//AA//gAAAAAAAAB//gB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA8PAAf+AAP8AAAAAB//gB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAADwAABgAAAAAAAAAADwAADwAADwAAHgAAPAAAeAAA8AAA4AAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AA8AAA8AAA8AAA8AAA8AAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AAAPAAAPAAAPAAAPAAAPAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAABwAADwAwAwBwAwDgAwHAAwOAAwcAD84AD9wAADngAHPwAOMwAcAwA4BwBwDgDgHADAOAAAPwAAPwAAAAAAAAAAAAAAAAAwAABwAADwAwAwBwAwDgAwHAAwOAAwcAD84AD9wAADgwAHBwAODwAcGwA4MwBwPwDgPwDAAwAAAwAAAwAAAAAAAAAAAAAAAAAGAAAPAAAPAAAGAAAAAAAAAAAGAAAGAAAPAAAPAAAfgAAfgAAfgAAfgAAfgAAfgAAfgAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHBwAPDwAeHgA8PAB4eADw8ADw8AB4eAA8PAAeHgAPDwAHBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg4ADw8AB4eAA8PAAeHgAPDwAPDwAeHgA8PAB4eADw8ADg4AAAAAAAAAAAAAAAAAqqqqAAAAVVVVAAAAqqqqAAAAVVVVAAAAqqqqAAAAVVVVAAAAqqqqAAAAVVVVAAAAqqqqAAAAVVVVAAAAqqqqAAAAVVVVAAAAqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVqqqqVVVVVVVV////qqqq////VVVV////qqqq////VVVV////qqqq////VVVV////qqqq////VVVV////qqqq////VVVV////qqqq////ADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwA//wA//wA//wA//wAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwA//wA//wA//wA//wAADwAADwAADwAADwA//wA//wA//wA//wAADwAADwAADwAADwAADwAADwAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PA/8PA/8PA/8PA/8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///A///A///A///AA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAAAAAAAA//wA//wA//wA//wAADwAADwAADwAADwA//wA//wA//wA//wAADwAADwAADwAADwAADwAADwAA8PAA8PAA8PAA8PAA8PAA8PA/8PA/8PA/8PA/8PAAAPAAAPAAAPAAAPA/8PA/8PA/8PA/8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAAAAAAAA///A///A///A///AAAPAAAPAAAPAAAPA/8PA/8PA/8PA/8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PA/8PA/8PA/8PA/8PAAAPAAAPAAAPAAAPA///A///A///A///AAAAAAAAAAAAAAAAAAAAAAAAAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PA///A///A///A///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAADwAADwA//wA//wA//wA//wAADwAADwAADwAADwA//wA//wA//wA//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//wA//wA//wA//wAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAD//AD//AD//AD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////ADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAD//AD//AD//AD//ADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwA////////////////ADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAAD//AD//AD//AD//ADwAADwAADwAADwAAD//AD//AD//AD//ADwAADwAADwAADwAADwAADwAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8P/A8P/A8P/A8P/A8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8P/A8P/A8P/A8P/A8AAA8AAA8AAA8AAA///A///A///A///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///A///A///A///A8AAA8AAA8AAA8AAA8P/A8P/A8P/A8P/A8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PA/8P//8P//8P//8P/AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA/8P//8P//8P//8P/A8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8P/A8P/A8P/A8P/A8AAA8AAA8AAA8AAA8P/A8P/A8P/A8P/A8PAA8PAA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAA8PAA8PAA8PAA8PAA8PAA8PA/8P//8P//8P//8P/AAAAAAAAAAAAAAAA/8P//8P//8P//8P/A8PAA8PAA8PAA8PAA8PAA8PAADwAADwAADwAADwAADwAADwA////////////////AAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAA////////////////ADwAADwAADwAADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////A8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA///A///A///A///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAADwAADwAADwAADwAAD//AD//AD//AD//ADwAADwAADwAADwAAD//AD//AD//AD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//AD//AD//AD//ADwAADwAADwAADwAAD//AD//AD//AD//ADwAADwAADwAADwAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///A///A///A///A8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PA/8P//8P//8P//8P/A8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAADwAADwAADwAADwAADwAADwA////////////////AAAAAAAAAAAAAAAA////////////////ADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwAADwA//wA//wA//wA//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//AD//AD//AD//ADwAADwAADwAADwAADwAADwAADwAADwAADwAADwA////////////////////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////////////////////////////////////////AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AAAA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//AA//////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPxwAf7wA8fgA4PAA4HAA4HAA4HAA4HAA4PAA8fgAf7wAPxwAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4OAA48AA48AA4OAA4HAA4HAA4HAA4HAA4PAA/+AA/8AA4AAA4AAAcAAAOAAAAAAAAAAAAAAAAAAA//AA//AA8PAA8PAA8PAA8PAA8AAA8AAA8AAA8AAA8AAA8AAA8AAA8AAA8AAA8AAA8AAA8AAAAAAAAAAAAAAAAAAAAAAAAAAB//gB//gAcOAAcOAAcOAAcOAAcOAAcOAAcOAAcOAAcOAAcOAAcOAAcOAAcOAAcPIAcH4AcDwAAAAAAAAAAAAAAAAAAAAAAAAD/8AD/8ABwMABwMAA4MAA4MAAcAAAcAAAOAAAOAAAcAAAcAAA4MAA4MABwMABwMAD/8AD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAP/wAcOAA4HAA4HAA4HAA4HAA4HAA4HAAcOAAP8AAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA4HAA8PAA//AA/7gA7xwA4AAA4AABwAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAfDgA/ngB//ABh+AAB4AAB4AAB4AAB4AAB4AAB4AAB4AAA8gAAfgAAPAAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AADwAADwAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA8PAAf+AAP8AADwAADwAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAADwAAP8AAf+AA8PAA4HAB4HgBwDgBwDgB//gB//gBwDgBwDgB4HgA4HAA8PAAf+AAP8AADwAAAAAAAAAAAAAAAAAAAAAAAAAAf+AA//AB4HgBwDgBwDgBwDgBwDgBwDgBwDgB4HgA8PAAeeAAOcAAOcAAOcAAOcAB+fgB+fgAAAAAAAAAAAAAAAAAAAAAAAAAD+AAH/AAPAAAPAAAHgAAHwAAP4AAf8AA8eAA4OAA4PAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/PAB//gD3zwDjhwDhhwDhhwDhxwDz7wB//gA8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAADgAP/AAf+AA8fAB4/gBxzgBzjgB/HgA+PAAf+AA/8ABwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAP/AAfAAAeAAA8AAA4AAA4AAA4AAA//AA//AA4AAA4AAA4AAA8AAAeAAAfAAAP/AAD+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA+fAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAA8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AA//AAAAAAAAAAAAAAAAAA//AA//AAAAAAAAAAAAAAAAAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAABgAABgAABgAABgAA//AA//AABgAABgAABgAABgAABgAAAAAAAAAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAHgAADwAAB4AAA8AAAeAAAeAAA8AAB4AADwAAHgAAPAAAAAAAAAAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAB4AADwAAHgAAPAAAeAAAeAAAPAAAHgAADwAAB4AAA8AAAAAAAAAA//AA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAB/gADzwADhwADhwADhwADgAADgAADgAADgAADgAADgAADgAADgAADgAADgAADgAADgAADgAADgAABwAABwAABwAABwAABwAABwAABwAABwAABwAABwAABwAABwAABwAABwADhwADhwADhwADzwAB/gAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAADwAADwAABgAAAAAAAAAA//AA//AAAAAAAAAABgAADwAADwAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+BgB/BwDzhwDhzwDg/gBgfAAAAAAAAAA+BgB/BwDzhwDhzwDg/gBgfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAf+AA8PAA4HAA4HAA4HAA4HAA8PAAf+AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAH8AAH8AAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAPAAAMAAAMAAAMAAAMAAAMAAAMAAgMAAwMAA4MAAcMAAOMAAHMAADsAAB8AAA8AAAcAAAAAAAAAAAAAAAAAAAAAAAAADjwAB34AA+8AA88AA88AA88AA88AA88AA88AA88AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAP4AAc8AAYcAAA8AAB4AADwAAHgAAP8AAf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA').split("").map(c => c.charCodeAt(0).toString(2).padStart(8, '0')).join("").split("").map(c => Number(c)));
// let font = new Uint8Array(147456);
// let fontLoaded = false;

const FontEditor = () => {
    
    // Open Font Editor Window
        const html = String.raw; // used for minification
        modal.open(html`
        <style>
            #charsTable {
                background-color: #e0edff;
                border: solid 1px #000;
                user-select: none;
                border-collapse: collapse;
                line-height: 0;
            }
            #charsTable td, #charsTable th {
                width: 24px;
                height: 24px;
                padding: 2px;
            }
            #charsTable td:hover {
                background-color: rgba(255, 255, 255, 0.5);
            }
            #fontEditorBody {
                display: flex;
            }
            #charEditor {
                padding-left: 20px;
            }
            #charEditorTable {
                user-select: none;
                border-collapse: collapse;
                cursor: crosshair;
            }
            #charEditorTable td {
                width: 18px;
                height: 18px;
                padding: 0;
                border: 1px dotted #888;
            }
            #charEditorChar {
                font-family: monospace;
                font-weight: bold;
                white-space: pre;
            }
        </style>
        <p>
            <button id="fontImportPNGButton">${i18n`Import font from PNG image`}</button>
            <button id="fontImportMIFButton">${i18n`Import font from MIF`}</button>
        </p>
        <div id="fontEditorBody">
            <table id="charsTable">
                <thead>
                <tr><th></th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7</th><th>8</th><th>9</th><th>A</th><th>B</th><th>C</th><th>D</th><th>E</th><th>F</th></tr>
                </thead>
                <tbody id="charsContainer">
                    
                </tbody>
            </table>
            <div id="charEditor">
                <div id="charEditorChar"></div>
                <table id="charEditorTable">
                    <tbody>
                    </tbody>
                </table>
                <p>
                    <button id="charEditorClearButton">${i18n`Clear`}</button>
                    <button id="charEditorInvertButton">${i18n`Invert`}</button>
                    <button id="charEditorCopyButton">${i18n`Copy`}</button>
                    <button id="charEditorPasteButton">${i18n`Paste`}</button>
                    <button id="charEditorSaveButton">${i18n`Save`}</button>
                </p>
            </div>
        </div>
        <p style="text-align: center">
            <a id="fontExportButton" class="button" target="_blank" download="font_memory.mif" href="javascript:" >${i18n`Export font to MIF`}</a>
        </p>
    `);
    
    const charDescription = c => `Char: ${cp437.toChar(c)} | Hex: ${c.toString(16).toUpperCase().padStart(2, '0')} | Dec: ${c}`;

    // Generate Canvas Table
    const charsCanvas = [];
    const charsContainer = document.getElementById("charsContainer");
    for (let y = 0, c = 0; y < 16; y++) {
        const tr = document.createElement("tr");
        const th = document.createElement("th");
        th.innerText = y.toString(16).toUpperCase();
        tr.appendChild(th);
        for (let x = 0; x < 16; x++) {
            const td = document.createElement("td");
            td.setAttribute("title", charDescription(c));
            const canvas = charsCanvas[c] = document.createElement("canvas");
            canvas.setAttribute("width", "24");
            canvas.setAttribute("height", "24");
            canvas.setAttribute("data-char", c);
            td.appendChild(canvas);
            tr.appendChild(td);
            c++;
        }
        charsContainer.appendChild(tr);
    }
    
    // Clicking in a character opens the character editor
    charsContainer.addEventListener("click", e => {
        if (e.target.hasAttribute("data-char")) {
            const c = Number(e.target.getAttribute("data-char"));
            charEditor.editChar(c);
        }
    });
    
    // Char Editor
    const charEditor = {
        selected: null,
        changed: false,
        clipboard: null,
        drawing: false,
        drawingAction: 0,
        cells: new Array(576),
        table: document.getElementById("charEditorTable"),
        editChar: (c, ignoreChanges) => {
            if (ignoreChanges || charEditor.editCharConfirm()) {
                charEditor.selected = c;
                charEditor.changed = false;
                for (let i = c * 576, j = 0; j < 576; i++, j++) {
                    charEditor.setCellState(charEditor.cells[j], font[i]);
                }
                document.getElementById("charEditorChar").innerText = charDescription(c);
            }
        },
        editCharConfirm: () => !charEditor.changed || confirm(i18n`You will lose the changes to the current character, continue?`), 
        setCellState: (cell, state) => cell.style.backgroundColor = state ? '#000' : '',
        toggleCellState: cell => charEditor.setCellState(cell, !charEditor.getCellState(cell)),
        getCellState: cell => cell.style.backgroundColor ? true : false
    };
    
    // Generate Char Editor
    for (let y = 0, i = 0; y < 24; y++) {
        const tr = document.createElement("tr");
        for (let x = 0; x < 24; x++) {
            const td = charEditor.cells[i] = document.createElement("td");
            td.setAttribute("data-cell", i);
            tr.appendChild(td);
            i++;
        }
        charEditor.table.appendChild(tr);
    }
       
    // Save character
    document.getElementById("charEditorSaveButton").addEventListener("click", () => {
        if (charEditor.selected) {
            const c = charEditor.selected;
            for (let i = c * 576, j = 0; j < 576; i++, j++) {
                font[i] = charEditor.getCellState(charEditor.cells[j]) ? 1 : 0;
            }
            printChar(c);
            charEditor.changed = false;
        }
    });
    
    // Copy pixels
    document.getElementById("charEditorCopyButton").addEventListener("click", () => {
        charEditor.clipboard = new Array(charEditor.cells.length);
        for (let i = 0; i < charEditor.cells.length; i++) {
            charEditor.clipboard[i] = charEditor.getCellState(charEditor.cells[i]);
        }
    });
    
    // Paste pixels
    document.getElementById("charEditorPasteButton").addEventListener("click", () => {
        if (!charEditor.clipboard) alert(i18n`Clipboard is empty.`);
        else {
            for (let i = 0; i < charEditor.cells.length; i++) {
                charEditor.setCellState(charEditor.cells[i], charEditor.clipboard[i]);
            }
            charEditor.changed = true;
        }
    });

    // Draw pixels
    charEditor.table.addEventListener("contextmenu", e => e.preventDefault());
    charEditor.table.addEventListener("mousedown", e => {
        console.log(e);
        charEditor.drawing = true;
        charEditor.drawingAction = e.which == 1 ? 1 : (e.which == 3 ? 0 : -1);
        charEditor.setCellState(e.target, charEditor.drawingAction);
        charEditor.changed = true;
        e.preventDefault();
    });
    document.addEventListener("mouseup", e => {
        charEditor.drawing = false;
    });
    charEditor.table.addEventListener("mouseover", e => {
        if (charEditor.drawing && e.target.hasAttribute("data-cell")) {
            if (charEditor.drawingAction == -1) charEditor.toggleCellState(e.target);
            else charEditor.setCellState(e.target, charEditor.drawingAction);
            charEditor.changed = true;
        }
    });
    
    // Clear all pixels
    document.getElementById("charEditorClearButton").addEventListener("click", () => {
        for (const cell of charEditor.cells) {
            charEditor.setCellState(cell, false);
        }
        charEditor.changed = true;
    });
    
    // Invert all pixels
    document.getElementById("charEditorInvertButton").addEventListener("click", () => {
        for (const cell of charEditor.cells) {
            charEditor.toggleCellState(cell);
        }
        charEditor.changed = true;
    });
        
    // Import from PNG
    document.getElementById("fontImportPNGButton").addEventListener("click", () => {
        UI.fileUploader.upload(async (file, getFileContent) => {
            loadPNG(await getFileContent(true));
        }, ".png"); 
    });
    
    // Import from MIF
    document.getElementById("fontImportMIFButton").addEventListener("click", () => {
        UI.fileUploader.upload(async (file, getFileContent) => {
            loadMIF(await getFileContent());
        }, ".mif"); 
    });
    
    // Export to MID
    document.getElementById("fontExportButton").addEventListener("click", e => {
        const mif = generateMIF(font, 16, 2, 1, 147456);
        createDownloadLink(e.target, "font_memory.mif", mif);
    });

    const generateFontFromPNG = (pngImage, charsPerLine = 255) => {
        const data = new Uint8Array(147456);
        const colorFreq = {};
        const decFromArray = c => (c[0] << 16) | (c[1] << 8) | c[2];
        const image = (() => {
            const image = new Array(pngImage.height);
            let i = 0;
            for (let y = 0; y < pngImage.height; y++) {
                image[y] = new Array(pngImage.width);
                for (let x = 0; x < pngImage.width; x++) {
                    //image[y][x] = [pngImage.data[i++], pngImage.data[i++], pngImage.data[i++], pngImage.data[i++]];
                    //const color = decFromArray(image[y][x]);
                    const color = (pngImage.data[i++] << 16) | (pngImage.data[i++] << 8) | pngImage.data[i++];
                    i++; // ignore alpha
                    image[y][x] = color;
                    if (color in colorFreq) colorFreq[color]++;
                    else colorFreq[color] = 1;
                }
            }
            return image;
        })();
        console.log("colorFreq", colorFreq);
        const colors = Object.keys(colorFreq).sort((a, b) => ((a, b) => a > b ? -1 : (b > a ? 1 : 0))(colorFreq[a], colorFreq[b]));
        if (colors.length < 2) return alert(i18n`Could not decode the PNG file.` + "\n\n" +
            i18n`Please make sure it contains at least 2 different colours.` + "\n\n" +
            i18n`Supported formats:\n- PNG-8 1~256 colored platte mode with transparency\n- PNG-24 RGBA mode`);
        const fontColor = Number(colors[1]);
        const xScale = pngImage.width / 384;
        const yScale = pngImage.height / 384;

        for (let c = 0, i = 0; c < 256; c++) {
            for (let y = 0; y < 24; y++) {
                for (let x = 0; x < 24; x++) {
                    const iy = Math.floor((Math.floor(c / 16) * 24 + y) * yScale);
                    const ix = Math.floor(((c % 16) * 24 + x) * xScale);
                    data[i++] = image[iy][ix] == fontColor ? 1 : 0;
                }
            }
        }
        return data;
    };
    
    const printChar = c => {
        var canvas = charsCanvas[c];
        var ctx = canvas.getContext('2d');
        ctx.fillStyle = 'rgb(0, 0, 0)';
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.imageSmoothingEnabled = false;

        let i = c * 576;
        for (let y = 0; y < 24; y++) {
            for (let x = 0; x < 24; x++) {
                if (font[i++]) ctx.fillRect(x, y, 1, 1);
            }
        }
    };

    const updateCanvas = () => {
        // Load chars into canvas
        for (let c = 0; c < 256; c++) {
            printChar(c);
        }
        charEditor.editChar(1, true);
    };
    
    const loadPNG = async pngData => {
         const pngImage = await PNG.decode(pngData);
        console.log("pngImage", pngImage);
        font = generateFontFromPNG(pngImage);
        updateCanvas();
    };
    
    const loadMIF = mif => {
        font = parseMIF(mif);
        updateCanvas();
    };
    
    updateCanvas();
    
    // Load default font
    // if (!fontLoaded) {
        // fetch('font_memory.mif').then(response => response.text().then(text => {
            // fontLoaded = true;
            // loadMIF(text);
        // }));
        // fetch('scripts/FontEditor/DefaultFont.txt').then(response => response.text().then(text => {
            //Base64 generated: btoa(String.fromCharCode(...font.join("").match(/.{8}/g).map(s => parseInt(s, 2))))
            // font = Uint8Array.from(atob(text).split("").map(c => c.charCodeAt(0).toString(2).padStart(8, '0')).join("").split("").map(c => Number(c)));
            // updateCanvas();
        // }));
    // }

    // Window Close Handler
    modal.onClose = () => charEditor.editCharConfirm();
};

document.getElementById("fontEditorLink").addEventListener("click", FontEditor);
